version : '3.8'
services:
  db:
    image: mysql:8.0
    container_name: grocery-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grocery
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grocery-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  
volumes:
  db_data: